version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            pipenv sync --dev

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      # Prepare environment for test
      - run:
          name: validate setup.py and install package
          command: |
            pipenv run python setup.py check -s
            pipenv run python setup.py install

      # run tests!
      - run:
          name: run tests on package
          command: |
            ./cc-test-reporter env
            ./cc-test-reporter before-build
            pipenv run python -m pytest --cov=easygoogle --cov-append --cov-config=.coveragerc --cov-report term --cov-report xml -v tests/
            # pipenv run coveralls
            ./cc-test-reporter after-build --exit-code $? --coverage-input-type "coverage.py"

      - run:
          name: Push to PyPi (if is tag)
          command: |
            pipenv run .circleci/twine_upload.sh

deployment:
  tag_build_for_cci2:
    # 1.0 style config for tag builds workaround
    # For context, see:
    # - https://discuss.circleci.com/t/build-on-tag/9864/30
    # - https://discuss.circleci.com/t/git-tag-deploys-in-2-0/9493/8
    # - https://circleci.com/gh/keybits/circulate/58#config/containers/0
    tag: /^[a-z]+-[0-9]+\.[0-9]+\.[0-9]+[ab]?[0-9]*$/
    commands:
      - true
